---
title: "HW01"
author: "B06305042"
date: "2017年10月14日"
output: html_document
---
library(dplyr)
library(ggplot2)
data = read.csv("titanic.csv", header=T, sep=",")

#分析票價和生存率的關係
temp1 = select(data,fare,survival)%>%
  filter(fare>=100)
asd = temp1[-which(temp1$survival==1),]
qwe = length(asd$survival==0)/length(temp1$survival)

temp2 = select(data,fare,survival) %>%
  filter(fare<=100)
zxc = temp2[-which(temp2$survival==1),]
fgh = length(zxc$survival==0)/length(temp2$survival)


#票價大於100者死亡率為0.423,而票價小於100者死亡率為0.647,可以猜測在事故發生時,票價較高者享有優先逃生的權力



#分析傭人的搭船地點,生存率,和class等級
temp3 = select(data,survival,gender,joined,class,job,fare) %>%
  filter(survival==1,class==1,job=='Personal Maid',gender==1)
temp4 = select(data,survival,gender,joined,class,job,age,fare) %>%
  filter(survival==1,class==1,job=='Personal Maid',gender==0)
group_by(temp3,joined) 


#從分析結果我們可以發現傭人多來自於Southampton和Cherbourg,可推知這2個地區較為富裕,有趣的一點是人傭的生存率居然高達100%,其生存率高的原因大概是跟著雇主,所以同樣享有優先逃生的權力
    
    
    
#class等級與存活率的比較
passenger = data[data$class %in% c(1,3),]
passenger = passenger[!passenger$fare == 9999,]
passenger = passenger[!passenger$age == 9999,]
head(passenger)

Class1 = select(passenger, survival, class) %>%
  filter(class == 1)
Class1alive = sum(Class1$survival == 1) 
Class1dead = sum(Class1$survival == 0) 
Class1total = length(Class1$survival) 
Class1survivalrate = Class1alive / Class1total
print (Class1survivalrate)
Class3 = select(passenger, survival, class) %>%
  filter(class == 3)
Class3alive = sum(Class3$survival == 1) 
Class3dead = sum(Class3$survival == 0) 
Class3total = length(Class3$survival) 
Class3survivalrate = Class3alive / Class3total
print (Class3survivalrate)

CLASS = data.frame(Class = c("Class1", "Class3"),
  survivalrate = c(Class1survivalrate, Class3survivalrate))
ggplot(data = CLASS, aes(x = Class, y = survivalrate, fill = Class)) + 
  geom_bar(stat = "identity")


             
#由結果推論等級越高，存活率越大,且Class1和Class3存活率快相差3倍

